channels:
    - defaults
    - conda-forge
    - microsoft
dependencies:
    - python=3.11
    - pip
    - pytest=7
    - nodejs=16
    - black
    - isort
    - codespell
    - pre-commit
    - pillow
    - numpy
    - markdown
    - pip:
          - playwright
          - pytest-playwright
          - pytest-xdist
          - pytest-instafail
          - pytest-random-order
          # We need Pyodide and micropip so we can import them in our Python
          # unit tests
          - pyodide_py==0.23.0
          - micropip==0.2.2
